# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eade63b791813710ee1a49734ba31cae72d912dc5dba59ed13ec4e2258de59ad458e90356318ef9132a2ce48fcf8b34a41fdd53fdec52e6d93645b82dd42c9b

test:
  secret_key_base: 77deebd750c94928fbd1e48f01e1488a56b1cb62ab3583336eade33e26ffc29da42132ab7e6371f1c066cb76e145ff2b74c4ee37092406221ddc64693b435ba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
